import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import yt_dlp
import time

# Function to convert Selenium cookies to Netscape format
def save_cookies_netscape_format(cookies, filename='cookies.txt'):
    with open(filename, 'w') as file:
        file.write("# Netscape HTTP Cookie File\n")
        file.write("# This file was generated by Selenium. Edit at your own risk.\n\n")

        for cookie in cookies:
            if 'expiry' in cookie:
                expiry = cookie['expiry']
            else:
                expiry = '0'
            domain = cookie['domain']
            path = cookie['path']
            secure = 'TRUE' if cookie['secure'] else 'FALSE'
            file.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{cookie['name']}\t{cookie['value']}\n")

# Initialize the WebDriver
options = Options()
options.add_argument("--headless")  # Run headless
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

try:
    # Go to YouTube and log in
    driver.get('https://youtube.com')

    # Wait for manual login (You need to manually login within the workflow)
    time.sleep(30)  # Adjust this as necessary for login

    # Extract cookies after logging in
    cookies = driver.get_cookies()

    # Print cookies to the terminal
    print("
