const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://youtube.com/login');

    // Automate the login process...

    // Extract cookies after logging in
    let cookies = await page.cookies();

    // Filter out cookies with an expires value of -1 (optional)
    cookies = cookies.filter(cookie => cookie.expires !== -1);

    // Start with the header lines required by the Netscape format
    let netscapeCookies = `# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by Puppeteer. Edit at your own risk.\n\n`;

    // Convert to Netscape format
 
