name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true
        default: 'https://www.youtube.com/watch?v=EXAMPLE'

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can choose your preferred Python version

      - name: Install dependencies
        run: |
          pip install selenium yt-dlp webdriver-manager

      - name: Run script to extract cookies and download video
        run: |
          python download_youtube_video.py ${{ github.event.inputs.video_url }}
